# Generated by Django 4.2.11 on 2024-05-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_showcase', models.CharField(max_length=200)),
                ('education', models.CharField(max_length=200)),
                ('work_experience', models.IntegerField()),
                ('experience', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=200)),
                ('skill_set', models.CharField(max_length=200)),
                ('contact_details', models.IntegerField(default=None)),
            ],
        ),
    ]
