# Generated by Django 4.2.11 on 2024-05-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact_details',
            field=models.IntegerField(),
        ),
    ]
